### PR TITLE
Add use https option

### PR DESCRIPTION
**Pull request by ackintosh**
Related issue: https://github.com/stormcat24/protodep/issues/45

Added a CLI flag to clone dependencies via HTTPS. :octocat: 

```
$ protodep up --use-https
$ protodep up -u
```

### CODE REVIEW

**Comment by ackintosh** [comment]
@stormcat24 Please let me know if you have any concerns about this PR. 😃

**Comment by mmlb** [comment]
@stormcat24 I'd love to see this in protodep too. The ssh identify setup doesn't really work for multiple users in a team that may not have the identity setup for repos.

**Comment by mmlb** [comment]
IMO shelling out to git is probably a better option and falling back to this logic in case git is missing (but imo it shouldn't be a big deal to say "depends on Git in PATH").

**Comment by stormcat24** [comment]
@mmlb Sorry for the late reply 🙏 
Thank you for your nice contribution.

**Comment by mmlb** [comment]
props go to @ackintosh

**Pull request merged**
