### PR TITLE
add SSH agent support

### PR DESCRIPTION
**Pull request by ewhauser**
This addresses #43 

Because of the logic in the command line flags today, my implementation would be a breaking change for anyone who is relying on using `protodep`'s default behavior and using SSH key w/o a password. However, it is my belief that not using the ssh agent by default best meets the principle of least surprise. Most command line tools just use the SSH agent by default and you only need to override the behavior if you want to use a specific PEM.

### CODE REVIEW

**Comment by ksato9700** [comment]
Thank you for the patch. It works in my side!
By the way, how can you set https method after applying patch? It is probably necessary to pull proto files from repositories having a read-only access.

**Comment by ewhauser** [comment]
Looks like I didn't handle that very well. The only way to use HTTPS is to pass in an invalid PEM file `-i does_not_exist`. Could add either a new flag for that or the SSH agent option depending on how it is preferred to handle it.

Based on the way `protodep` is currently written, the authentication choice is global -- you use one method for all of the repositories. A better choice for supporting mixed mode authentication would be to allow the specification of the transport in the repo string, i.e. `git+ssh://` or `https://`

**Comment by ksato9700** [comment]
You're right that only the way to specify https was to specify an invalid identity file. I also think it is probably better to specify the transport explicitly as a url.

**Comment by stormcat24** [comment]
Sorry for the late reply 🙏
I agree with these discussions about ssh-agent.

@ewhauser There is a conflict with the master branch now, can you resolve it?

**Review by stormcat24 — APPROVED** [review]
Great works!

**Comment by stormcat24** [comment]
@ewhauser I was able to resolve the conflict, so I'll merge it.
Thank you for your great work!

**Pull request merged**
